### ISSUE TITLE
PR 받으시나요?

### ISSUE THREAD

**Issue by neuwcodebox** [tistory/document-tistory-apis#1]
안녕하세요?
먼저 유용한 API 제공에 감사드립니다.
다만 사용 중 문서에서 누락된 부분과 오탈자를 발견해서 어려움이 있었습니다.
다른 분들도 같은 일을 겪지 않으셨음 해서 해당 부분을 수정하여 PR을 드리고 싶습니다.
혹시 받으시는지, 받으신다면 지침을 알려주실 수 있으신지 궁금합니다.
감사합니다.

**Comment by joostory** [comment]
오탈자 / 오류는 언제든 이슈 남겨주세요. pr 주시면 더 좋구요. 👍

**Comment by neuwcodebox** [comment]
감사합니다.
