### ISSUE TITLE
Implicit 방식 Oauth2.0 인증이 안됩니다.

### ISSUE THREAD

**Issue by boltlessengineer** [tistory/document-tistory-apis#6]
바로 오늘 아침까지만 해도 됐는데 19시 즈음부터 갑자기 안되네요
제가 등록한 앱 두개와 친구가 등록한 앱 하나 총 3개로 테스트해봤습니다.

```
https://www.tistory.com/oauth/authorize?client_id={app-id}&redirect_uri={callback}&response_type=token
```

👆 이 형식으로 GET 요청을 보내면

```
{callback}?error=unsupported_response_type
```

👆 이렇게 에러가 뜹니다.
tistory 깃허브 레포지터리에도 Implicit 방식 요청 예제는 없는 것 같은데 혹시 오류가 있는지 확인 부탁드립니다.

**Comment by sabarada** [comment]
어제 날짜로해서 깃 커밋 로그가 `Implicit 방식 API 지원 제거`가 있네요..
저도 안되서 확인하려 들어왔더니 ㅠ

**Comment by boltlessengineer** [comment]
<img width="485" alt="chrome_eeIeL75Por" src="https://user-images.githubusercontent.com/60088301/92074006-ffa21380-edef-11ea-9cb1-348563d95b77.png">
