### ISSUE TITLE
.

### ISSUE THREAD

**Issue by beardoggo** [tistory/document-tistory-apis#7]
.

**Comment by boltlessengineer** [comment]
콜백 url은  http://boltlessengineer.tistory.com을 넣었어요. 혹시 https로 되어있어서 안되시는거일수도 있으니 확인해보세요

일단 전 지금 확인해봤는데 잘 됩니다.

**Comment by beardoggo** [comment]
https://www.tistory.com/guide/api/manage/list에서 기존에 등록된 앱 삭제하고 새로운 클라이언트 ID와 Secreet 발급받아 해결
